# Generated by Django 2.2.4 on 2019-08-28 14:37

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=100)),
                ('modification_date', models.DateTimeField()),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('airtable_json', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('airtable_url', models.TextField(blank=True, null=True)),
                ('display_text', models.TextField(blank=True, null=True)),
                ('malus', models.DecimalField(decimal_places=6, max_digits=7, null=True)),
                ('category', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='practice',
            name='types',
        ),
        migrations.AddField(
            model_name='practice',
            name='types',
            field=models.ManyToManyField(to='data.PracticeType'),
        ),
    ]
