# Generated by Django 2.2.4 on 2019-08-28 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20190828_1437'),
    ]

    operations = [
        migrations.RenameField(
            model_name='practicetype',
            old_name='malus',
            new_name='penalty',
        ),
    ]
