# Generated by Django 2.2.4 on 2019-08-30 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20190828_1542'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AirtableRecords',
        ),
    ]
