# Generated by Django 2.2.4 on 2019-09-03 15:29

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_delete_airtablerecords'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice',
            name='weed_multipliers',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), blank=True, null=True, size=None),
        ),
    ]
