# Generated by Django 2.2.4 on 2019-09-06 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_auto_20190906_1347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='practice',
            old_name='cultures_whitelist',
            new_name='culture_whitelist',
        ),
        migrations.RenameField(
            model_name='practice',
            old_name='pests_whitelist',
            new_name='pest_whitelist',
        ),
        migrations.RenameField(
            model_name='practice',
            old_name='weeds_whitelist',
            new_name='weed_whitelist',
        ),
    ]
