# Generated by Django 2.2.4 on 2019-09-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_practice_glyphosate_multipliers'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice',
            name='needs_livestock',
            field=models.BooleanField(null=True),
        ),
    ]
