# Generated by Django 2.2.4 on 2019-10-03 15:59

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_practice_needs_livestock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=100)),
                ('modification_date', models.DateTimeField()),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('airtable_json', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('airtable_url', models.TextField(blank=True, null=True)),
                ('display_text', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Weed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=100)),
                ('modification_date', models.DateTimeField()),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('airtable_json', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('airtable_url', models.TextField(blank=True, null=True)),
                ('display_text', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('nature', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='practice',
            name='pest_multipliers',
        ),
        migrations.RemoveField(
            model_name='practice',
            name='pest_whitelist',
        ),
        migrations.RemoveField(
            model_name='practice',
            name='weed_multipliers',
        ),
        migrations.RemoveField(
            model_name='practice',
            name='weed_whitelist',
        ),
        migrations.CreateModel(
            name='WeedMultiplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multiplier', models.DecimalField(decimal_places=6, max_digits=7)),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Practice')),
                ('weed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Weed')),
            ],
        ),
        migrations.CreateModel(
            name='PestMultiplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multiplier', models.DecimalField(decimal_places=6, max_digits=7)),
                ('pest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Pest')),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Practice')),
            ],
        ),
        migrations.AddField(
            model_name='practice',
            name='pest_multipliers',
            field=models.ManyToManyField(related_name='pest_multipliers', related_query_name='pest_multipliers', through='data.PestMultiplier', to='data.Pest'),
        ),
        migrations.AddField(
            model_name='practice',
            name='pest_whitelist',
            field=models.ManyToManyField(to='data.Pest'),
        ),
        migrations.AddField(
            model_name='practice',
            name='weed_multipliers',
            field=models.ManyToManyField(related_name='weed_multipliers', related_query_name='weed_multipliers', through='data.WeedMultiplier', to='data.Weed'),
        ),
        migrations.AddField(
            model_name='practice',
            name='weed_whitelist',
            field=models.ManyToManyField(to='data.Weed'),
        ),
    ]
