# Generated by Django 2.2.4 on 2019-10-04 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_auto_20191003_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice',
            name='needs_deep_tillage',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='practice',
            name='needs_shallow_tillage',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
