# Generated by Django 2.2.4 on 2019-10-05 07:31

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_auto_20191004_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practice',
            name='pest_multipliers',
        ),
        migrations.AddField(
            model_name='practice',
            name='pest_multipliers',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), blank=True, null=True, size=None),
        ),
        migrations.RemoveField(
            model_name='practice',
            name='weed_multipliers',
        ),
        migrations.AddField(
            model_name='practice',
            name='weed_multipliers',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), blank=True, null=True, size=None),
        ),
    ]
