# Generated by Django 2.2.4 on 2019-10-05 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_auto_20191005_0731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weedmultiplier',
            name='practice',
        ),
        migrations.RemoveField(
            model_name='weedmultiplier',
            name='weed',
        ),
        migrations.AlterField(
            model_name='pest',
            name='external_id',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='weed',
            name='external_id',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.DeleteModel(
            name='PestMultiplier',
        ),
        migrations.DeleteModel(
            name='WeedMultiplier',
        ),
    ]
