# Generated by Django 2.2.4 on 2019-10-05 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_auto_20191005_0830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practice',
            name='pest_whitelist',
        ),
        migrations.RemoveField(
            model_name='practice',
            name='weed_whitelist',
        ),
    ]
