# Generated by Django 2.2.4 on 2019-10-07 08:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0019_auto_20191007_0838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='culture',
            name='sowing_month',
        ),
        migrations.AddField(
            model_name='culture',
            name='sowing_months',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
    ]
