# Generated by Django 2.2.4 on 2019-10-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0020_auto_20191007_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice',
            name='balances_sowing_period',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
