# Generated by Django 2.2.4 on 2019-11-14 15:30

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0021_practice_balances_sowing_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscardAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('practice_airtable_id', models.CharField(max_length=100)),
                ('reason', models.TextField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
