# Generated by Django 2.2.4 on 2019-11-14 16:48

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0022_discardaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='discardaction',
            name='answers',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
