# Generated by Django 2.2.4 on 2019-11-16 14:32

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0023_discardaction_answers'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupCount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('counter', models.IntegerField(default=0)),
                ('group', models.IntegerField(unique=True)),
            ],
        ),
    ]
