# Generated by Django 2.2.8 on 2020-01-21 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0025_referercount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='practice',
            old_name='image_url',
            new_name='airtable_image_url',
        ),
        migrations.AddField(
            model_name='practice',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
