# Generated by Django 2.2.8 on 2020-01-22 16:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0027_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='practice_external_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None),
        ),
    ]
