# Generated by Django 2.2.9 on 2020-01-28 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0028_auto_20200122_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice',
            name='short_title',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
