# Generated by Django 2.2.9 on 2020-02-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0029_practice_short_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
