# Generated by Django 2.2.9 on 2020-02-06 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0030_resource_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practice',
            name='airtable_image_url',
        ),
    ]
