# Generated by Django 3.0.3 on 2020-03-16 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0033_auto_20200316_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='farmer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiments', to='data.Farmer'),
        ),
    ]
