# Generated by Django 3.0.3 on 2020-03-16 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0034_auto_20200316_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiment',
            name='additional_details',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='experiment',
            name='origin',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='livestock_number',
            field=models.TextField(null=True),
        ),
    ]
