# Generated by Django 3.0.3 on 2020-03-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0035_auto_20200316_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='output',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='surface',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='surface_cultures',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='surface_meadows',
            field=models.TextField(null=True),
        ),
    ]
