# Generated by Django 3.0.3 on 2020-03-16 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0037_auto_20200316_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='personnel',
            field=models.TextField(null=True),
        ),
    ]
