# Generated by Django 3.0.3 on 2020-03-17 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0041_experimentimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='profession',
        ),
    ]
