# Generated by Django 3.0.3 on 2020-03-17 15:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0042_remove_farmer_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='profession',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None),
        ),
    ]
