# Generated by Django 3.0.3 on 2020-03-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0044_auto_20200319_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='text_links',
            field=models.TextField(null=True),
        ),
    ]
