# Generated by Django 3.0.3 on 2020-03-20 12:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0045_farmer_text_links'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='text_links',
        ),
        migrations.AddField(
            model_name='farmer',
            name='links',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None),
        ),
    ]
