# Generated by Django 3.0.3 on 2020-03-26 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0050_auto_20200324_0933'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='videos/')),
                ('experiment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='data.Experiment')),
            ],
        ),
    ]
