# Generated by Django 3.0.3 on 2020-03-26 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0051_experimentvideo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experimentvideo',
            old_name='image',
            new_name='video',
        ),
    ]
