# Generated by Django 3.0.3 on 2020-04-14 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0056_farmer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='modification_date',
        ),
        migrations.AddField(
            model_name='farmer',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
