# Generated by Django 3.0.3 on 2020-04-14 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0057_auto_20200414_0909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmer',
            old_name='modified_date',
            new_name='modification_date',
        ),
        migrations.AlterField(
            model_name='culture',
            name='modification_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='modification_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='weed',
            name='modification_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
