# Generated by Django 3.0.3 on 2020-04-17 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0060_auto_20200414_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='name',
            field=models.TextField(unique=True),
        ),
    ]
