# Generated by Django 3.0.3 on 2020-04-19 11:21

import django.contrib.postgres.fields
from django.db import migrations, models


def migrate_surface_type(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Experiment = apps.get_model('data', 'Experiment')
    for experiment in Experiment.objects.all():
        experiment.surface_type = [] if not experiment.surface_type_char else [x.strip() for x in experiment.surface_type_char.split(',')]
        experiment.save()


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0061_auto_20200417_1535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experiment',
            old_name='surface_type',
            new_name='surface_type_char',
        ),
        migrations.AddField(
            model_name='experiment',
            name='surface_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None),
        ),
        migrations.RunPython(migrate_surface_type),
        migrations.RemoveField(
            model_name='experiment',
            name='surface_type_char'
        )
    ]
