# Generated by Django 3.0.3 on 2020-04-19 15:40

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0062_auto_20200419_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='agriculture_types',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='groups',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='links',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='production',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None),
        ),
    ]
