# Generated by Django 3.0.3 on 2020-04-19 15:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0063_auto_20200419_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[("Changement important de l'exploitation", "Changement important de l'exploitation"), ("Amélioration de l'existant", "Amélioration de l'existant"), ('Maladies', 'Maladies'), ('Insectes et ravageurs', 'Insectes et ravageurs'), ('Adventices', 'Adventices'), ('Environnement & biodiversité', 'Environnement & biodiversité'), ('Diversification', 'Diversification'), ('Autonomie fourragère', 'Autonomie fourragère'), ('Productivité', 'Productivité'), ('Organisation du travail', 'Organisation du travail'), ('Réduction des charges', 'Réduction des charges'), ('Autre', 'Autre')], max_length=255), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='xp_type',
            field=models.TextField(choices=[("Changement important de l'exploitation", "Changement important de l'exploitation"), ("Amélioration de l'existant", "Amélioration de l'existant")], null=True),
        ),
    ]
