# Generated by Django 3.0.3 on 2020-04-19 20:53

import data.forms
from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0065_auto_20200419_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='links',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='surface_type',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='agriculture_types',
            field=data.forms.ChoiceArrayField(base_field=models.TextField(choices=[('Agriculture Biologique', 'Agriculture Biologique'), ('Agriculture de Conservation des Sols', 'Agriculture de Conservation des Sols'), ('Techniques Culturales Simplifiées', 'Techniques Culturales Simplifiées'), ('Labour occasionnel', 'Labour occasionnel'), ('Agroforesterie', 'Agroforesterie'), ('Conventionnel', 'Conventionnel'), ('Cahier des charges industriel', 'Cahier des charges industriel'), ('Label qualité', 'Label qualité'), ('Autre', 'Autre')]), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='groups',
            field=data.forms.ChoiceArrayField(base_field=models.CharField(choices=[('DEPHY', 'DEPHY'), ('GIEE', 'GIEE'), ('30000', '30000'), ('CETA', 'CETA'), ('Groupe de coopérative', 'Groupe de coopérative'), ('Groupe de négoce', 'Groupe de négoce'), ("Groupe de chambre d'agriculture", "Groupe de chambre d'agriculture"), ('Groupe de voisins', 'Groupe de voisins'), ('CUMA', 'CUMA'), ('Autre', 'Autre')], max_length=200), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='production',
            field=data.forms.ChoiceArrayField(base_field=models.CharField(choices=[('Grandes cultures', 'Grandes cultures'), ('Cultures industrielles', 'Cultures industrielles'), ('Élevage allaitant', 'Élevage allaitant'), ('Élevage laitier', 'Élevage laitier'), ('Cultures légumières', 'Cultures légumières'), ('Vigne', 'Vigne'), ('Autre', 'Autre')], max_length=100), blank=True, null=True, size=None),
        ),
    ]
