# Generated by Django 3.0.3 on 2020-04-20 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0067_auto_20200420_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentimage',
            name='label',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='experimentvideo',
            name='label',
            field=models.TextField(null=True),
        ),
    ]
