# Generated by Django 3.0.3 on 2020-04-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0068_auto_20200420_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmimage',
            name='label',
            field=models.TextField(null=True),
        ),
    ]
