# Generated by Django 3.0.3 on 2020-05-02 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0072_auto_20200430_0933'),
        ('data', '0072_auto_20200502_1023'),
    ]

    operations = [
    ]
