# Generated by Django 3.0.3 on 2020-05-02 14:52

import data.forms
from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0073_merge_20200502_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='additional_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='approved',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='control_presence',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='equipment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='execution',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='investment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='links',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='method',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='objectives',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='ongoing',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='origin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='results',
            field=models.TextField(blank=True, choices=[("XP qui fonctionne, elle est intégrée à l'exploitation", "XP qui fonctionne, elle est intégrée à l'exploitation"), ("XP prometteuse, en cours d'amélioration", "XP prometteuse, en cours d'amélioration"), ('XP abandonnée, les résultats ne sont pas satisfaisants', 'XP abandonnée, les résultats ne sont pas satisfaisants'), ('XP en suspens, les conditions ne sont plus réunies', 'XP en suspens, les conditions ne sont plus réunies'), ('XP qui commence, les premiers résultats sont à venir', 'XP qui commence, les premiers résultats sont à venir')], null=True),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='results_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='surface',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='surface_type',
            field=data.forms.ChoiceArrayField(base_field=models.TextField(choices=[('Toutes les surfaces', 'Toutes les surfaces'), ('Plusieurs parcelles', 'Plusieurs parcelles'), ('Une parcelle', 'Une parcelle'), ('Des bandes', 'Des bandes'), ('Des carrés', 'Des carrés')]), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='tags',
            field=data.forms.ChoiceArrayField(base_field=models.CharField(choices=[("Changement important de l'exploitation", "Changement important de l'exploitation"), ("Amélioration de l'existant", "Amélioration de l'existant"), ('Maladies', 'Maladies'), ('Insectes et ravageurs', 'Insectes et ravageurs'), ('Adventices', 'Adventices'), ('Environnement & biodiversité', 'Environnement & biodiversité'), ('Diversification', 'Diversification'), ('Autonomie fourragère', 'Autonomie fourragère'), ('Productivité', 'Productivité'), ('Organisation du travail', 'Organisation du travail'), ('Réduction des charges', 'Réduction des charges'), ('Autre', 'Autre')], max_length=255), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='temporality',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='xp_type',
            field=models.TextField(blank=True, choices=[("Changement important de l'exploitation", "Changement important de l'exploitation"), ("Amélioration de l'existant", "Amélioration de l'existant")], null=True),
        ),
        migrations.AlterField(
            model_name='experimentimage',
            name='label',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experimentvideo',
            name='label',
            field=models.TextField(blank=True, null=True),
        ),
    ]
