# Generated by Django 3.0.3 on 2020-05-11 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0078_auto_20200504_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiment',
            name='additional_details',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='execution',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='method',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='temporality',
        ),
        migrations.AlterField(
            model_name='experiment',
            name='name',
            field=models.TextField(),
        ),
    ]
