# Generated by Django 3.0.3 on 2020-05-11 15:21

import data.forms
from django.db import migrations, models

def populate_livestock_types(apps, schema_editor):
    Farmer = apps.get_model('data', 'Farmer')
    for farmer in Farmer.objects.all():
        if farmer.livestock_type:
            types = [x.strip().capitalize() for x in farmer.livestock_type.split(',')]
            farmer.livestock_types = types
            farmer.save()

class Migration(migrations.Migration):

    dependencies = [
        ('data', '0079_auto_20200511_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='livestock_types',
            field=data.forms.ChoiceArrayField(base_field=models.TextField(choices=[('Bovin', 'Bovin'), ('Ovin', 'Ovin'), ('Caprin', 'Caprin'), ('Avicole', 'Avicole'), ('Porcin', 'Porcin'), ('Autre', 'Autre')]), blank=True, default=list, null=True, size=None),
        ),
        migrations.RunPython(populate_livestock_types)
    ]
