# Generated by Django 3.0.3 on 2020-05-12 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0080_farmer_livestock_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='livestock_type',
        ),
    ]
