# Generated by Django 3.0.3 on 2020-05-29 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0082_auto_20200527_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='cgu_approved',
            field=models.BooleanField(default=False),
        ),
    ]
