# Generated by Django 3.0.3 on 2020-06-04 09:05

from django.db import migrations, models

def populate_existing_farmers(apps, schema_editor):
    Farmer = apps.get_model('data', 'Farmer')
    for farmer in Farmer.objects.all():
        farmer.onboarding_shown = True
        farmer.save()


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0083_farmer_cgu_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='onboarding_shown',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(populate_existing_farmers),
    ]
