# Generated by Django 3.0.7 on 2020-06-22 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0085_auto_20200618_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='farm_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
