# Generated by Django 3.0.7 on 2020-06-29 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0086_farmer_farm_name'),
    ]

    operations = [
        migrations.RunSQL(
            "CREATE SEQUENCE farmer_sequence_number",
            reverse_sql="DROP SEQUENCE IF EXISTS farmer_sequence_number",
            elidable=False
        ),
        migrations.AddField(
            model_name='farmer',
            name='sequence_number',
            field=models.IntegerField(null=True),
        ),
        migrations.RunSQL(
            "CREATE SEQUENCE experiment_sequence_number",
            reverse_sql="DROP SEQUENCE IF EXISTS experiment_sequence_number",
            elidable=False
        ),
        migrations.AddField(
            model_name='experiment',
            name='sequence_number',
            field=models.IntegerField(null=True),
        ),
    ]
