# Generated by Django 3.0.7 on 2020-06-29 17:04

from django.db import migrations, models
from data.models import farmer, experiment

class Migration(migrations.Migration):

    dependencies = [
        ('data', '0088_auto_20200629_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='sequence_number',
            field=models.IntegerField(default=farmer.get_next_increment, editable=False, unique=True)
        ),
        migrations.AlterField(
            model_name='experiment',
            name='sequence_number',
            field=models.IntegerField(default=experiment.get_next_increment, editable=False, unique=True)
        ),
        migrations.AlterField(
            model_name='experiment',
            name='name',
            field=models.TextField(max_length=70),
        )
    ]
