# Generated by Django 3.0.7 on 2020-07-06 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0091_auto_20200703_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='short_name',
            field=models.TextField(blank=True, help_text="Si ce champ est présent, il sera utilisé pour l'URL", max_length=30, null=True),
        ),
    ]
