# Generated by Django 3.0.7 on 2020-07-29 12:33

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0099_experiment_cultures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='cultures',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, null=True, size=None),
        ),
    ]
