# Generated by Django 3.0.7 on 2020-08-03 09:31

import data.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0100_auto_20200729_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='tags',
            field=data.forms.ChoiceArrayField(base_field=models.CharField(choices=[('Maladies', 'Maladies'), ('Insectes et ravageurs', 'Insectes et ravageurs'), ('Adventices', 'Adventices'), ('Environnement & biodiversité', 'Environnement & biodiversité'), ('Diversification', 'Diversification'), ('Autonomie fourragère', 'Autonomie'), ('Productivité', 'Productivité'), ('Organisation du travail', 'Organisation du travail'), ('Réduction des charges', 'Réduction des charges'), ('Sol et fertilisation', 'Sol et fertilisation'), ('Autre', 'Autre')], max_length=255), blank=True, default=list, null=True, size=None),
        ),
    ]
