# Generated by Django 3.1 on 2020-08-11 14:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0102_auto_20200810_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='airtable_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='discardaction',
            name='answers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='airtable_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='airtable_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mechanism',
            name='airtable_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pest',
            name='airtable_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='practice',
            name='airtable_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='practice',
            name='culture_multipliers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='practice',
            name='department_multipliers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='practice',
            name='glyphosate_multipliers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='practice',
            name='pest_multipliers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='practice',
            name='soil_type_multipliers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='practice',
            name='weed_multipliers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='practicegroup',
            name='airtable_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='practicetype',
            name='airtable_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='airtable_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='simulatorculture',
            name='airtable_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weed',
            name='airtable_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
