# Generated by Django 3.1 on 2020-08-18 14:48

import data.forms
from django.db import migrations, models

def migrate_experiment_tag(apps, schema_editor):
    Experiment = apps.get_model('data', 'Experiment')
    for experiment in Experiment.objects.all():
        if 'Autonomie fourragère' in experiment.tags:
            experiment.tags.remove('Autonomie fourragère')
            experiment.tags.append('Autonomie')
            experiment.save()


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0103_auto_20200811_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='tags',
            field=data.forms.ChoiceArrayField(base_field=models.CharField(choices=[('Maladies', 'Maladies'), ('Insectes et ravageurs', 'Insectes et ravageurs'), ('Adventices', 'Adventices'), ('Environnement & biodiversité', 'Environnement & biodiversité'), ('Diversification', 'Diversification'), ('Autonomie', 'Autonomie'), ('Productivité', 'Productivité'), ('Organisation du travail', 'Organisation du travail'), ('Réduction des charges', 'Réduction des charges'), ('Sol et fertilisation', 'Sol et fertilisation'), ('Autre', 'Autre')], max_length=255), blank=True, default=list, null=True, size=None),
        ),
        migrations.RunPython(migrate_experiment_tag),
    ]
