# Generated by Django 3.1.1 on 2020-09-07 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0105_experiment_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiment',
            name='approved',
        ),
        migrations.AlterField(
            model_name='experiment',
            name='state',
            field=models.TextField(choices=[('Brouillon', 'Brouillon'), ('En attente de validation', 'En attente de validation'), ('Validé', 'Validé')], db_index=True, default='Brouillon'),
        ),
    ]
