# Generated by Django 3.1.1 on 2020-09-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0107_auto_20200923_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='self_created',
            field=models.BooleanField(default=False),
        ),
    ]
