# Generated by Django 3.1.1 on 2020-09-30 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0108_farmer_self_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='farmer',
            options={'ordering': ['-creation_date']},
        ),
    ]
