# Generated by Django 3.1.1 on 2020-11-06 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0110_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='active',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
