# Generated by Django 3.1.1 on 2020-11-19 08:18

from django.db import migrations, models

def migrate_can_send_messages(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Farmer = apps.get_model('data', 'Farmer')
    for farmer in Farmer.objects.all():
        farmer.can_send_messages = farmer.approved or farmer.sent_messages.count() > 0
        farmer.save()


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0113_theme_copyright'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='can_send_messages',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(migrate_can_send_messages),
    ]
