# Generated by Django 3.1.1 on 2020-11-19 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0114_farmer_can_send_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='pending_delivery',
            field=models.BooleanField(default=False),
        ),
    ]
