# Generated by Django 3.1.1 on 2020-12-11 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0115_message_pending_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
