# Generated by Django 3.2 on 2021-09-28 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0116_message_notified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='practices',
        ),
        migrations.DeleteModel(
            name='DiscardAction',
        ),
        migrations.DeleteModel(
            name='GroupCount',
        ),
        migrations.DeleteModel(
            name='Pest',
        ),
        migrations.RemoveField(
            model_name='practice',
            name='main_resource',
        ),
        migrations.RemoveField(
            model_name='practice',
            name='mechanism',
        ),
        migrations.RemoveField(
            model_name='practice',
            name='practice_groups',
        ),
        migrations.RemoveField(
            model_name='practice',
            name='secondary_resources',
        ),
        migrations.RemoveField(
            model_name='practice',
            name='types',
        ),
        migrations.DeleteModel(
            name='RefererCount',
        ),
        migrations.DeleteModel(
            name='SimulatorCulture',
        ),
        migrations.DeleteModel(
            name='Weed',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='airtable_json',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='airtable_json',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='airtable_url',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Mechanism',
        ),
        migrations.DeleteModel(
            name='Practice',
        ),
        migrations.DeleteModel(
            name='PracticeGroup',
        ),
        migrations.DeleteModel(
            name='PracticeType',
        ),
        migrations.DeleteModel(
            name='Resource',
        ),
    ]
